# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ef88a8c2aa28628fe2531a5b3e2bb49f2c7b68e2bc2cb9d26c5aeb76b39d6881a4654252d687d8dcfbb45cb6098edb33d57fc31f2e9e531adfecb9c8be6e53

test:
  secret_key_base: 3c035d267bef56c2ba15020c756809fef767917058de144bb48ca5c79dfe31a1f513d2c90fb4b399180f2ec4c654838cfbb9dad0e63cdd5481aa7e52d7eee675

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
